### ISSUE TITLE
How you add the ε from the keyboard

### ISSUE THREAD

**Issue by sedici16** [joeylemon/nfa-to-dfa#13]
I like this tool however I cannot find a way to add the epsylon ε when adding a new transition. Can you help?

**Comment by joeylemon** [comment]
When adding a new transition and prompted to type the symbol, pressing the "e" button on the keyboard will automatically be translated to ε within the application:

<img width="273" alt="Screen Shot 2022-01-20 at 2 55 10 PM" src="https://user-images.githubusercontent.com/8845512/150412349-750549c2-3168-4408-bd43-08bc438d5c55.png">

**Comment by sedici16** [comment]
thanks I have eventually found out by trying, it is a good tool, you should
add this to the instruction, and possibility to name your own states

**Comment by joeylemon** [comment]
PR #14 adding instructions on how to create ε-transitions
