### ISSUE TITLE
Object "transitions"

### ISSUE THREAD

**Issue by christinapap13** [joeylemon/nfa-to-dfa#17]
Hello, i wnat ask this:
I can only see that is the fa.js file in the constructor you have written in the comments that transitions is an object, but where do you define  the properties of this object and where do you define what the form of the transition look like (for example [starting stete][symbol]=>[final states])?

Τhank you very much in advance.

**Comment by joeylemon** [comment]
Unfortunately we didn't use TypeScript or anything similar to give us structured forms to look at at a glance. However, we can see from the unit tests that the transition object should look like this:
https://github.com/joeylemon/nfa-to-dfa/blob/76046f7785ac6a014f5d231b33324d7e0c5be221/src/js/test/fsa.test.js#L7-L21

In this example, if we are at state `1` and receive the input of symbol `b`, the FSA can transition to state `2`. If we are at state `2` and receive the input of symbol `a`, the FSA can transition to states `2` or `3`.
