### ISSUE TITLE
Recursive / Multiple epsilon transitions can result in incorrect DFAs

### ISSUE THREAD

**Issue by MeMyselfMirai** [joeylemon/nfa-to-dfa#20]
While tinkering with the program, I noticed that an NFA representing the regex string `a*b*c*` is not transcribed correctly.
![image](https://github.com/joeylemon/nfa-to-dfa/assets/55056986/c1aa0f35-ea58-4e15-bafb-68bbd717d0e6)
Specifically, the program does not recursively check what states can be reached by epsilon transitions; in this case, `1,2,3` should be reachable, but the program believes that `1,2` is correct:
![image](https://github.com/joeylemon/nfa-to-dfa/assets/55056986/2fc17c44-8cae-4927-81c1-9dba065d7035)
This not only results in redundant states, but also means the resulting DFA can be incorrect. In this case, the DFA rejects the string `ccccc`, even though it is valid according to the original regex rule. 

It seems the error stems from the lack of recursion in the [epsilon closure function](https://github.com/joeylemon/nfa-to-dfa/blob/master/src/js/fsa/fsa.js#L117-L125).

**Comment by joeylemon** [comment]
Thank you for your contribution @AD417, this issue will be fixed in #21
